version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: store
    ports: 
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - store

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - store 
networks:
  store:
volumes:
  db_data: