version: '3.8'
services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'store'
      POSTGRES_PASSWORD: 'admin'
volumes:
  db_data: