export enum Permissions {
    SuperAdmin = "SuperAdmin",
    ReadProduct = "ReadProduct",
    DeleteProduct = "DeleteProduct",
    UpdateProduct = "UpdateProduct",
    CreateProduct = "CreateProduct",
    ReadCollection = "CreateProduct",
    CreateCollection = "CreateCollection",
    DeleteCollection = "DeleteCollection",
    UpdateCollection = "UpdateCollection",
    ReadAsset = "ReadAsset",
    CreateAsset = "CreateAsset",
    DeleteAsset = "DeleteAsset",
    UpdateAsset = "UpdateAsset",
    ReadCustomer = "ReadCustomer",
    CreateCustomer = "CreateCustomer",
    DeleteCustomer = "DeleteCustomer",
    UpdateCustomer = "UpdateCustomer",
    ReadPromotion = "ReadPromotion",
    CreatePromotion = "CreatePromotion",
    DeletePromotion = "DeletePromotion",
    UpdatePromotion = "UpdatePromotion",
    ReadAdministrator = "ReadAdministrator",
    CreateAdministrator = "CreateAdministrator",
    DeleteAdministrator = "DeleteAdministrator",
    UpdateAdministrator = "UpdateAdministrator",
    ReadRole = "UpdateAdministrator",
    CreateRole = "UpdateAdministrator",
    DeleteRole = "UpdateAdministrator",
    UpdateRole = "UpdateAdministrator"
}

