export const permissionLang = {
   "ReadProduct": "Xem sản phẩm",
   "CreateProduct": "Tạo sản phẩm",
   "DeleteProduct": "Xóa sản phẩm",
   "UpdateProduct": "Cập nhật sản phẩm",
   "ReadCategory": "Xem danh mục",
   "CreateCategory": "Tạo danh mục",
   "DeleteCategory": "Xóa danh mục",
   "UpdateCategory": "Cập nhật danh mục",
   "ReadAsset": "Xem ảnh",
   "CreateAsset": "Tạo ảnh",
   "DeleteAsset": "Xóa ảnh",
   'ReadOrder': "Xem đơn hàng",
   'DeleteOrder': "Xóa đơn hàng",
   'UpdateOrder': "Cập nhật đơn hàng",
   'CreateOrder': "Tạo đơn hàng",
   "ReadCustomer": "Xem khách hàng",
   "CreateCustomer": "Tạo khách hàng",
   "DeleteCustomer": "Xóa khách hàng",
   "UpdateCustomer": "Cập nhật khách hàng",
   "ReadPromotion": "Xem khuyến mãi",
   "CreatePromotion": "Tạo khuyến mãi",
   "DeletePromotion": "Xóa khuyến mãi",
   "UpdatePromotion": "Cập nhật khuyến mãi",
   "CreateCart": "Thêm sản phẩm giỏ hàng",
   "UpdateCart": "Cập nhật giỏ hàng",
   "DeleteCart": "Xóa sản phẩm trong giỏ hàng",
   "ReadCart": "Xem giỏ hàng",
   "ReadRate": "Xem đánh giá",
   "CreateRate": "Tạo đánh giá",
   "SuperAdmin": "SuperAdmin"
}